apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: medbot-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    # existing rule for medbot.local
    - host: medbot.local
      http:
        paths:
          - path: /classify
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: 80
          - path: /history
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 3001

    # new rule for localhost
    - host: localhost
      http:
        paths:
          - path: /classify
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: 80
          - path: /history
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 3001
